language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: "T1kEfLg+xcFI2MgeESWvLOHeXHyps9bpx2hzRbsNzu7vWeeAhpFKFeE62lKKDWGIzLT9HpbqfHig9Z8ZPKzJPSZhLPYwPefEdqgBGuOhAugzFXVua71LVddIK3Fr1BYTZ7X5cDwT4XUtDltU/U6svYAWzu/HlYg23sQ7RXInaETizSMr2cD9L47aBvrNR9S5HApOL6XRdyjrlVpEZTjtrwx4Sq/l/1eB4mfpBk43uJuXsjLCMplLArv+fTQKJxCpKvjYUfk6pnasSEvOS//Kr1DtdtrW4ZtXslcObpSc8QrkXfUOu3tuZj0MTDGkhcShzJkzTTABNbYm9WCCF5gGP9CteX/5D3TO2GyTIrGJicFt2d3wamsqUK8xmvvud3uCXQe3y3NsuAtlsJGst7sWWMYnIqJxG9llLrwNlLRtN/dvda+CBZ0kP9EwFunUUIcgWRLiErBrntaeeeHYjdvJU/Mv7NlKCM1ZAAZWBI43/SwchrBV+haoZHJl6U8hRyq/zajkFQUx6UZPeNeYhrN7Zhp2G4Z8cvOQErp397I5AxvlExe+H/TM+s828EcciCq/fmhaUrg1GgPEZcqtWu9/XMVcfJ9dhPW544EXXA8uUJXfQ7RRe/SjhsJUfaMAZoj1+evRgblmD/aDM5t5kjHC7Ohp4AuLBHtYk9mSyX4JFfE="
